### ISSUE TITLE
practica 2

### ISSUE THREAD

**Issue by carlos0716c** [SistemasTecTlaxiaco/practica2#1]
[PRÁCTICA_2 visual.pdf](https://github.com/SistemasTecTlaxiaco/practica2/files/10775236/PRACTICA_2.visual.pdf)

**Comment by saul19bautista** [comment]
Portada (notable) falto agregar el nombre de la practica  22 puntos
procedimiento ( notable) falto agregar más procedimiento a cada una de las figuras 22 puntos
Figuras, ilustraciones y fotografía (notable) falto agregarle más descripción a cada una de ellas 20 puntos
Resultados y conclusiones (excelente) 25 puntos
total 89/100
calificación 17.8%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
